//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Leave Type.
        /// </summary>
        internal static string AddLeaveType {
            get {
                return ResourceManager.GetString("AddLeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Role.
        /// </summary>
        internal static string AddRole {
            get {
                return ResourceManager.GetString("AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Team.
        /// </summary>
        internal static string AddTeam {
            get {
                return ResourceManager.GetString("AddTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        internal static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add_btn {
            get {
                return ResourceManager.GetString("Add_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Surname.
        /// </summary>
        internal static string Add_input1 {
            get {
                return ResourceManager.GetString("Add_input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Add_input2 {
            get {
                return ResourceManager.GetString("Add_input2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Add_input3 {
            get {
                return ResourceManager.GetString("Add_input3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Role.
        /// </summary>
        internal static string Add_input4 {
            get {
                return ResourceManager.GetString("Add_input4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Manager.
        /// </summary>
        internal static string Add_input5 {
            get {
                return ResourceManager.GetString("Add_input5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Second Manager.
        /// </summary>
        internal static string Add_input6 {
            get {
                return ResourceManager.GetString("Add_input6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string Add_tbl_h1 {
            get {
                return ResourceManager.GetString("Add_tbl_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Name.
        /// </summary>
        internal static string Add_tbl_h2 {
            get {
                return ResourceManager.GetString("Add_tbl_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persons.
        /// </summary>
        internal static string Add_tbl_h3 {
            get {
                return ResourceManager.GetString("Add_tbl_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Add_tbl_h4 {
            get {
                return ResourceManager.GetString("Add_tbl_h4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string Add_tbl_h5 {
            get {
                return ResourceManager.GetString("Add_tbl_h5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string AdminText {
            get {
                return ResourceManager.GetString("AdminText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Leave Requests.
        /// </summary>
        internal static string AllRequest_title {
            get {
                return ResourceManager.GetString("AllRequest_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        internal static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        internal static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select two dates to view leaves.
        /// </summary>
        internal static string BetweenTwoDatesMsg {
            get {
                return ResourceManager.GetString("BetweenTwoDatesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Confirmation_tbl_th1 {
            get {
                return ResourceManager.GetString("Confirmation_tbl_th1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave ID.
        /// </summary>
        internal static string Default_approvals_table_th1 {
            get {
                return ResourceManager.GetString("Default_approvals_table_th1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        internal static string Default_approvals_table_th2 {
            get {
                return ResourceManager.GetString("Default_approvals_table_th2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string Default_approvals_table_th3 {
            get {
                return ResourceManager.GetString("Default_approvals_table_th3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string Default_approvals_table_th4 {
            get {
                return ResourceManager.GetString("Default_approvals_table_th4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Default_approvals_table_th5 {
            get {
                return ResourceManager.GetString("Default_approvals_table_th5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting Approver.
        /// </summary>
        internal static string Default_approvals_table_th6 {
            get {
                return ResourceManager.GetString("Default_approvals_table_th6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Level.
        /// </summary>
        internal static string Default_approvals_table_th7 {
            get {
                return ResourceManager.GetString("Default_approvals_table_th7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Copyright &amp;copy; 2017 &lt;a href=&quot;http://optiim.com&quot;&gt;OPTiiM&lt;/a&gt;.&lt;/strong&gt; All rights
        ///    reserved..
        /// </summary>
        internal static string Default_copyright {
            get {
                return ResourceManager.GetString("Default_copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        internal static string Default_homepage {
            get {
                return ResourceManager.GetString("Default_homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        internal static string Default_leave_table_th1 {
            get {
                return ResourceManager.GetString("Default_leave_table_th1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Year.
        /// </summary>
        internal static string Default_leave_table_th2 {
            get {
                return ResourceManager.GetString("Default_leave_table_th2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Leave Right.
        /// </summary>
        internal static string Default_leave_table_th3 {
            get {
                return ResourceManager.GetString("Default_leave_table_th3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Used Leave.
        /// </summary>
        internal static string Default_leave_table_th4 {
            get {
                return ResourceManager.GetString("Default_leave_table_th4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Leave Left.
        /// </summary>
        internal static string Default_leave_table_th5 {
            get {
                return ResourceManager.GetString("Default_leave_table_th5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Leave Status.
        /// </summary>
        internal static string Default_leave_table_th6 {
            get {
                return ResourceManager.GetString("Default_leave_table_th6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Summary.
        /// </summary>
        internal static string Default_leave_table_th7 {
            get {
                return ResourceManager.GetString("Default_leave_table_th7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Start Date.
        /// </summary>
        internal static string Default_leave_table_WorkStartDate {
            get {
                return ResourceManager.GetString("Default_leave_table_WorkStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Leave Requests.
        /// </summary>
        internal static string Default_request_table_title {
            get {
                return ResourceManager.GetString("Default_request_table_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string Details_input1 {
            get {
                return ResourceManager.GetString("Details_input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string Details_input2 {
            get {
                return ResourceManager.GetString("Details_input2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Details_input3 {
            get {
                return ResourceManager.GetString("Details_input3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Details.
        /// </summary>
        internal static string Details_title {
            get {
                return ResourceManager.GetString("Details_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string DropdownValue_No {
            get {
                return ResourceManager.GetString("DropdownValue_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string DropdownValue_Yes {
            get {
                return ResourceManager.GetString("DropdownValue_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Role.
        /// </summary>
        internal static string EditRole {
            get {
                return ResourceManager.GetString("EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Team.
        /// </summary>
        internal static string EditTeam {
            get {
                return ResourceManager.GetString("EditTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        internal static string ExportToExcelText {
            get {
                return ResourceManager.GetString("ExportToExcelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial User.
        /// </summary>
        internal static string FinancialUserText {
            get {
                return ResourceManager.GetString("FinancialUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave App Support.
        /// </summary>
        internal static string LeaveAppSupport {
            get {
                return ResourceManager.GetString("LeaveAppSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Date.
        /// </summary>
        internal static string LeaveDate {
            get {
                return ResourceManager.GetString("LeaveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string LeaveDescription {
            get {
                return ResourceManager.GetString("LeaveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Duration.
        /// </summary>
        internal static string LeaveDuration {
            get {
                return ResourceManager.GetString("LeaveDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow get leave even resource has not got any leave right..
        /// </summary>
        internal static string LeavePolicies_AllowLeaveIfZero {
            get {
                return ResourceManager.GetString("LeavePolicies_AllowLeaveIfZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many days can be get leave before?.
        /// </summary>
        internal static string LeavePolicies_LeaveDuration {
            get {
                return ResourceManager.GetString("LeavePolicies_LeaveDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type.
        /// </summary>
        internal static string LeaveType {
            get {
                return ResourceManager.GetString("LeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type (TR).
        /// </summary>
        internal static string LeaveTypeTR {
            get {
                return ResourceManager.GetString("LeaveTypeTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Icon.
        /// </summary>
        internal static string LocationIcon {
            get {
                return ResourceManager.GetString("LocationIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        internal static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location (TR).
        /// </summary>
        internal static string LocationTR {
            get {
                return ResourceManager.GetString("LocationTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with Google.
        /// </summary>
        internal static string Login_btn {
            get {
                return ResourceManager.GetString("Login_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Login_language_en {
            get {
                return ResourceManager.GetString("Login_language_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        internal static string Login_language_en_value {
            get {
                return ResourceManager.GetString("Login_language_en_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Login_language_lbl {
            get {
                return ResourceManager.GetString("Login_language_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        internal static string Login_language_tr {
            get {
                return ResourceManager.GetString("Login_language_tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr.
        /// </summary>
        internal static string Login_language_tr_value {
            get {
                return ResourceManager.GetString("Login_language_tr_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to start your session.
        /// </summary>
        internal static string Login_lbl {
            get {
                return ResourceManager.GetString("Login_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPTiiM İzinApp.
        /// </summary>
        internal static string Login_title {
            get {
                return ResourceManager.GetString("Login_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LogoutText {
            get {
                return ResourceManager.GetString("LogoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string ManagerText {
            get {
                return ResourceManager.GetString("ManagerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Role.
        /// </summary>
        internal static string Menu_AddRole {
            get {
                return ResourceManager.GetString("Menu_AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins.
        /// </summary>
        internal static string Menu_Admins {
            get {
                return ResourceManager.GetString("Menu_Admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Leaves.
        /// </summary>
        internal static string Menu_all {
            get {
                return ResourceManager.GetString("Menu_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Approvals.
        /// </summary>
        internal static string Menu_approvals {
            get {
                return ResourceManager.GetString("Menu_approvals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Menu_dashboard {
            get {
                return ResourceManager.GetString("Menu_dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions.
        /// </summary>
        internal static string Menu_Definitions {
            get {
                return ResourceManager.GetString("Menu_Definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Team.
        /// </summary>
        internal static string Menu_FinancialTeam {
            get {
                return ResourceManager.GetString("Menu_FinancialTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Policies.
        /// </summary>
        internal static string Menu_LeavePolicies {
            get {
                return ResourceManager.GetString("Menu_LeavePolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Types.
        /// </summary>
        internal static string Menu_LeaveTypeManagement {
            get {
                return ResourceManager.GetString("Menu_LeaveTypeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Responsibles.
        /// </summary>
        internal static string Menu_LocationResponsibles {
            get {
                return ResourceManager.GetString("Menu_LocationResponsibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string Menu_management {
            get {
                return ResourceManager.GetString("Menu_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managerial Leave.
        /// </summary>
        internal static string Menu_ManagerialLeaveEntry {
            get {
                return ResourceManager.GetString("Menu_ManagerialLeaveEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managers.
        /// </summary>
        internal static string Menu_Managers {
            get {
                return ResourceManager.GetString("Menu_Managers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Menu_reports {
            get {
                return ResourceManager.GetString("Menu_reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Leaves.
        /// </summary>
        internal static string Menu_reports_li1 {
            get {
                return ResourceManager.GetString("Menu_reports_li1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Leaves.
        /// </summary>
        internal static string Menu_reports_li2 {
            get {
                return ResourceManager.GetString("Menu_reports_li2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Based Leaves.
        /// </summary>
        internal static string Menu_reports_li3 {
            get {
                return ResourceManager.GetString("Menu_reports_li3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaves Between Dates.
        /// </summary>
        internal static string Menu_reports_li4 {
            get {
                return ResourceManager.GetString("Menu_reports_li4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Request.
        /// </summary>
        internal static string Menu_request {
            get {
                return ResourceManager.GetString("Menu_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string Menu_RoleManagement {
            get {
                return ResourceManager.GetString("Menu_RoleManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Managers.
        /// </summary>
        internal static string Menu_SecondManagers {
            get {
                return ResourceManager.GetString("Menu_SecondManagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        internal static string Menu_staff {
            get {
                return ResourceManager.GetString("Menu_staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Roles.
        /// </summary>
        internal static string Menu_SystemRoles {
            get {
                return ResourceManager.GetString("Menu_SystemRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        internal static string Menu_TeamManagement {
            get {
                return ResourceManager.GetString("Menu_TeamManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Menu_UserManagement {
            get {
                return ResourceManager.GetString("Menu_UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No leave to display..
        /// </summary>
        internal static string myLeaveHasData {
            get {
                return ResourceManager.GetString("myLeaveHasData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No leave to be approved..
        /// </summary>
        internal static string PendingApprovalHasData {
            get {
                return ResourceManager.GetString("PendingApprovalHasData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Leaves.
        /// </summary>
        internal static string Report_tbl_th1 {
            get {
                return ResourceManager.GetString("Report_tbl_th1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Report_tbl_th2 {
            get {
                return ResourceManager.GetString("Report_tbl_th2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Based Total Leave Requests.
        /// </summary>
        internal static string Report_title {
            get {
                return ResourceManager.GetString("Report_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Request_btn {
            get {
                return ResourceManager.GetString("Request_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add half day to selected leave..
        /// </summary>
        internal static string Request_chkbox {
            get {
                return ResourceManager.GetString("Request_chkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It provides take half day leave..
        /// </summary>
        internal static string Request_chkbox1 {
            get {
                return ResourceManager.GetString("Request_chkbox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string Request_drop {
            get {
                return ResourceManager.GetString("Request_drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        internal static string Request_drop1 {
            get {
                return ResourceManager.GetString("Request_drop1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Request_drop2 {
            get {
                return ResourceManager.GetString("Request_drop2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add File.
        /// </summary>
        internal static string Request_file {
            get {
                return ResourceManager.GetString("Request_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Request Form.
        /// </summary>
        internal static string Request_form_title {
            get {
                return ResourceManager.GetString("Request_form_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Half Day.
        /// </summary>
        internal static string Request_href1 {
            get {
                return ResourceManager.GetString("Request_href1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Report.
        /// </summary>
        internal static string Request_href2 {
            get {
                return ResourceManager.GetString("Request_href2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half Day.
        /// </summary>
        internal static string Request_href3 {
            get {
                return ResourceManager.GetString("Request_href3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string Request_input1 {
            get {
                return ResourceManager.GetString("Request_input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string Request_input2 {
            get {
                return ResourceManager.GetString("Request_input2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string Request_input3 {
            get {
                return ResourceManager.GetString("Request_input3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string Request_input4 {
            get {
                return ResourceManager.GetString("Request_input4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type.
        /// </summary>
        internal static string Request_input5 {
            get {
                return ResourceManager.GetString("Request_input5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Description.
        /// </summary>
        internal static string Request_lbl {
            get {
                return ResourceManager.GetString("Request_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Duration (Day).
        /// </summary>
        internal static string Request_lbl1 {
            get {
                return ResourceManager.GetString("Request_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Request_lbl2 {
            get {
                return ResourceManager.GetString("Request_lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Leave Undertaking.
        /// </summary>
        internal static string Request_msj {
            get {
                return ResourceManager.GetString("Request_msj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///                                                    To Optiim Software Services / Optiim Business Solutions
        ///
        ///I want to use leave for  --- days based on my annual leave which is not beyond to me yet between ----- and ----- dates. I consent that not paying money of my advance leave days to me in case of ending of business contract in any reason.
        ///
        ///&lt;/p&gt;.
        /// </summary>
        internal static string Request_msj1 {
            get {
                return ResourceManager.GetString("Request_msj1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the contract..
        /// </summary>
        internal static string Request_msj2 {
            get {
                return ResourceManager.GetString("Request_msj2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read, I accept..
        /// </summary>
        internal static string Request_msj3 {
            get {
                return ResourceManager.GetString("Request_msj3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string Request_tbl_td1 {
            get {
                return ResourceManager.GetString("Request_tbl_td1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string Request_tbl_td2 {
            get {
                return ResourceManager.GetString("Request_tbl_td2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string Request_tbl_td3 {
            get {
                return ResourceManager.GetString("Request_tbl_td3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string Request_tbl_td4 {
            get {
                return ResourceManager.GetString("Request_tbl_td4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible Location.
        /// </summary>
        internal static string ResponsibleLocation {
            get {
                return ResourceManager.GetString("ResponsibleLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string RoleText {
            get {
                return ResourceManager.GetString("RoleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Manager.
        /// </summary>
        internal static string SecondManagerText {
            get {
                return ResourceManager.GetString("SecondManagerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Team.
        /// </summary>
        internal static string SelectTeam {
            get {
                return ResourceManager.GetString("SelectTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string StatusText {
            get {
                return ResourceManager.GetString("StatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Name.
        /// </summary>
        internal static string TeamNameText {
            get {
                return ResourceManager.GetString("TeamNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Leaves.
        /// </summary>
        internal static string TwoDates_btn {
            get {
                return ResourceManager.GetString("TwoDates_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaves Between Dates.
        /// </summary>
        internal static string TwoDates_title {
            get {
                return ResourceManager.GetString("TwoDates_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string UserActivate {
            get {
                return ResourceManager.GetString("UserActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UserEdit_input {
            get {
                return ResourceManager.GetString("UserEdit_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string UserEdit_input1 {
            get {
                return ResourceManager.GetString("UserEdit_input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string UserEdit_input2 {
            get {
                return ResourceManager.GetString("UserEdit_input2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string UserEdit_input3 {
            get {
                return ResourceManager.GetString("UserEdit_input3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Manager.
        /// </summary>
        internal static string UserEdit_input4 {
            get {
                return ResourceManager.GetString("UserEdit_input4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string UserEdit_input5 {
            get {
                return ResourceManager.GetString("UserEdit_input5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        internal static string UserEdit_msj {
            get {
                return ResourceManager.GetString("UserEdit_msj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string UserStartDate {
            get {
                return ResourceManager.GetString("UserStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
